export const products = [
  {
    id: 1,
    name: "Iphone Pro 7 (s_id-2)",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 2,
    name: "AIRDOPES (s_id-5)",
    description: "",
    price: 19.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/airdopes.webp"),
  },
  {
    id: 3,
    name: "Galaxy-S23 (s_id-5)",
    description: "",
    price: 29.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/Galaxy-S23.jpg"),
  },
  {
    id: 4,
    name: "headphone (s_id-2) ",
    description: "",
    price: 29.99,
    quantity: 2,
    paymentMethod: "phonepay",
    imgSrc: require("../img/hhh.jpg"),
  },
  {
    id: 5,
    name: "Applewatch (s_id-5)",
    description: "",
    price: 29.99,
    quantity: 2,
    paymentMethod: "cash",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 6,
    name: "ultra (s_id-2)",
    description: "",
    price: 29.99,
    quantity: 1,
    paymentMethod: "Google pay",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 7,
    name: "Iphone Pro 7 (s_id-7)",
    description: "",
    price: 29.99,
    quantity: 3,
    paymentMethod: "paytm",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 8,
    name: "Iphone Pro 7 (s_id-6)",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 9,
    name: "Iphone Pro 7 (s_id-3)",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 10,
    name: "Iphone Pro 7",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 11,
    name: "Iphone Pro 7",
    description: "1.hello this is iphone promax 2.this is big as huge",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 12,
    name: "Iphone Pro 7",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 13,
    name: "Iphone Pro 7",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 14,
    name: "Iphone Pro 7",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
  {
    id: 15,
    name: "Iphone Pro 7",
    description: "",
    price: 9.99,
    quantity: 2,
    paymentMethod: "Credit Card",
    imgSrc: require("../img/AppleWatch.jpg"),
  },
];
